/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.rabbit.project01;

public class App {
  public static void main(String[] args) {

    //<=======================================intro===============================================>
    java.util.Scanner keyboardInput = new java.util.Scanner(System.in);

    while (true) {
      int menuNo = keyboardInput.nextInt();
      keyboardInput.nextLine();

      if (menuNo == 0) {
        break;
      } else if (menuNo == 1) {
      } else if (menuNo == 2) {
      } else {
      }
    }
    keyboardInput.close();
  }
}
